### ISSUE TITLE
When you planning to publish book?

### ISSUE THREAD

**Issue by P9avel** [PacktPublishing/Modern-Distributed-Tracing-in-.NET#1]
Hi, When you planning to publish book? i am waant to buy it

**Comment by rajat-packt** [comment]
Hey @P9avel, thanks for showing interest in our product, we are hoping to publish his title in Q4 of this year.
You can pre-order a copy here: https://www.amazon.com/Modern-Distributed-Tracing-NET-observability/dp/1837636133
